// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCro7K8L7vm31Ulnl1UythV0_JA0chPGUA',
    appId: '1:190811670513:web:3a66686f1c26649d7f6650',
    messagingSenderId: '190811670513',
    projectId: 'exam-e736c',
    authDomain: 'exam-e736c.firebaseapp.com',
    storageBucket: 'exam-e736c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8NHpaHzD82FhlhibU4ebp64orOUezKRM',
    appId: '1:190811670513:android:362e094804a8ba727f6650',
    messagingSenderId: '190811670513',
    projectId: 'exam-e736c',
    storageBucket: 'exam-e736c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehCIOx_FofSCf32tdt8HW3SClAOL-nA4',
    appId: '1:190811670513:ios:4ac5af253237d5507f6650',
    messagingSenderId: '190811670513',
    projectId: 'exam-e736c',
    storageBucket: 'exam-e736c.appspot.com',
    iosBundleId: 'com.example.advFlutterFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehCIOx_FofSCf32tdt8HW3SClAOL-nA4',
    appId: '1:190811670513:ios:4ac5af253237d5507f6650',
    messagingSenderId: '190811670513',
    projectId: 'exam-e736c',
    storageBucket: 'exam-e736c.appspot.com',
    iosBundleId: 'com.example.advFlutterFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCro7K8L7vm31Ulnl1UythV0_JA0chPGUA',
    appId: '1:190811670513:web:62b3aa795c60dd967f6650',
    messagingSenderId: '190811670513',
    projectId: 'exam-e736c',
    authDomain: 'exam-e736c.firebaseapp.com',
    storageBucket: 'exam-e736c.appspot.com',
  );
}
